version: '3'

services:
  transmission:
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - $PWD/test/transmission/:/data
    env_file:
      - $PWD/dist/transmission.env

  web:
    image: treppo/nginx-cloudflare-ddns:latest
    read_only: true
    volumes:
      - /tmp/nginx:/var/tmp/nginx
      - $PWD/test/web/html:/var/www/html/:ro
      - $PWD/test/web/cache/dynamic-dns:/var/cache/dynamic-dns
      - $PWD/test/web/cache/nginx:/var/cache/nginx
    env_file:
      - $PWD/dist/ddns.env
    ports:
      - "8080:8080"
